# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in VishnuPages.gemspec
gemspec

gem "rake", "~> 13.0"

gem "jekyll"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
end